### ISSUE TITLE
Need a Usery Logo

### ISSUE THREAD

**Issue by lhaig** [lhaig/usery#11]
Usery needs a logo. I hope someone will step in to assist.

**Comment by mirzazulfan** [comment]
Hi @lhaig I've designed a logo for your project, if you need to change please let me know. Best Regard.
![usery](https://user-images.githubusercontent.com/36124339/48995413-54741d00-f17a-11e8-850f-ecafc2557f66.png)

**Comment by lhaig** [comment]
Hi @mirzazulfan This looks great.

Can you let me know why you chose the colors?

**Comment by mirzazulfan** [comment]
Hi @lhaig thanks for your response, I chose that color to represent a box and letter u/usery. If you like it, i'll sent you file (logomark, logotype, etc) or if you need to change the colors i'll change like you want. Best Regard.

**Comment by lhaig** [comment]
@mirzazulfan Thanks fo rthis. It would be great if I could havce a favion.ico and perhaps the source so I can ad this to the repository. 
Do you perhaps want to add a pull request for the files? 
We can add it to docs/images ?

Thanks for the help.

**Comment by mirzazulfan** [comment]
Sure, Im glad you liked it, i'll organize the files and upload all of them, as soon as possible. :+1:

**Comment by lhaig** [comment]
Great thanks. Now I need to create the webpage for this

**Comment by mirzazulfan** [comment]
Hi @lhaig ,, I've created a pr #21 ,, you can download all files [here](https://drive.google.com/drive/folders/1Hw_LMJ5s7ngi2LM7oImgCjcqdckofeaI?ogsrc=32)

Best Regard.

**Comment by lhaig** [comment]
Thank you
